#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### This script will be executed when package uninstalled and upgraded.
### Actions after package uninstalled.
### ex. remove garbage files.

UDEV_RULES=/usr/lib/udev/rules.d/70-kaku-tpc.rules

rm -f /usr/local/bin/kaku-tpc-server

if [ -w ${UDEV_RULES} ]; then
    rm -f ${UDEV_RULES}
    udevadm control --reload-rules
fi
